
#ifndef SIM_GAME_COLOR_ENUMS
#define SIM_GAME_COLOR_ENUMS

enum color_pair {THIS_ONE_DOESNT_WORK, 
		  BORDER_TEXT, WHITE_TEXT, CYAN_TEXT, GREEN_TEXT, GREY_TEXT, PINK_TEXT, YELLOW_TEXT,
                  BRIGHT_GREY_TEXT, BLOODY_TEXT, DARK_GREEN_TEXT, RED_SOLID, BLUE_SOLID, GREEN_SOLID,
                  GREY_SOLID, GOLD_SOLID, FOREST_SOLID};
enum colors {MC_BROWN = 17, MC_WHITE, MC_GREY, MC_PINK, MC_YELLOW, MC_BRIGHT_GREY, MC_BLOOD, MC_DARK_GREEN,
             MC_BRIGHT_RED, MC_BLUE, MC_GOLD, MC_FOREST};

#endif
